#For full documentation of the parameters in this file, and a list of all the
#parameters available for TrajectoryPlannerROS, please see
#http://www.ros.org/wiki/base_local_planner

# If I don't know what the acceleration limits of a robot are, I'll take the time to write a script that commands max #translational and rotational velocity to the motors for some period of time, look at the reported velocity from odometry #assuming the odometry gives a reasonable estimate of this), and derive the acceleration limits from that. Setting these #parameters reasonably often saves me a lot of time later.



TrajectoryPlannerROS:

  dwa: true #use the Dynamic Window Approach
  prune_plan: true
  global_frame_id: /odom #Should be set to the same frame as the local costmap's global frame

  #Set the acceleration limits of the robot in meters/sec^2  
  acc_lim_x: 0.5
  acc_lim_theta: 2 

  #Set the velocity limits of the robot
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 0.8
  min_vel_theta: -0.8
  min_in_place_vel_theta: 0.4
  escape_vel: -0.1
  
  holonomic_robot: false

  #Set the tolerance on achieving a goal. With bad localazation put hight tolerence.
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.09 

  #Forward Simulation Parameters
  #We'll configure how long and with what granularity we'll forward simulate trajectories
  sim_time: 1.5 # 2 * (goal_tolerance) >  ( min_vel * sim_time ) ... ore else the robot wont move
  sim_granularity: 0.025

  #The number of samples to use when exploring the x and theta velocity space
  vx_samples: 13 # for DWA planner 8 - 15 depending on the processing power. This allows for non-circular curves. 
  vtheta_samples: 20


  #Parameters for scoring trajectories 
  publish_cost_grid_pc: true  # publish the cost used when planning as pointcloud2 at <name>/cost_cloud topic
  meter_scoring: true
  forward_point_distance: 0.325 # default 0.325. The distance from the center point of robot to place an additional scoring point
  pdist_scale: 0.72 #weight on how much should stay close to path 
  gdist_scale: 0.68 #weight on how much should attempt to reach is local goal, also controls speed.
  occdist_scale: 0.02 #weight on how much should attempt to avoid obstacles (in my experience leave like that!)


 


